version: "3.8"
services:
  app:
    build: .
    # l'image doit préparer /app/data pour l'user
    user: "1000:1000"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=change-me-in-prod
      - ADMIN_DEFAULT_EMAIL=admin@example.com
      - ADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data:
